#ifndef AUTODIDACT_MODULES_AGENT_INCLUDE_CONSTANTS_HPP_
#define AUTODIDACT_MODULES_AGENT_INCLUDE_CONSTANTS_HPP_

#include <map>

enum ConnectorEnum
{
    acpc,
    slumbot,
    pokerstar,
};

#endif //AUTODIDACT_MODULES_AGENT_INCLUDE_CONSTANTS_HPP_
